# See: /usr/share/doc/mpd/mpdconf.example
# author zzm
# date 2026-02-02

music_directory "~/Music"
playlist_directory "~/.config/mpd/playlists"

bind_to_address "127.0.0.1"

auto_update "yes"
restore_paused "yes"

db_file "~/.config/mpd/mpd.db"
log_file "~/.config/mpd/mpd.log"
pid_file "~/.config/mpd/mpd.pid"
state_file "~/.config/mpd/mpdstate"

audio_output {
    type "pipewire"
    name "Pipewire Sound Sever"
}

# visualization
audio_output {
    type "fifo"
    name "Visualaizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
